In [2]:
import pandas as pd
import numpy as np

from sklearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV

from sklearn.feature_extraction.text import TfidfVectorizer

from sklearn.metrics import classification_report

In [9]:
import pandas as pd

train = pd.read_csv("train_processed.csv")

train.head()

,text,rating,tokens,stemmed,lemmatized,text_stem,text_lemma,review_length
0,this place is terrible the people in charge ar...,2,"['place', 'terrible', 'people', 'charge', 'wor...","['place', 'terribl', 'peopl', 'charg', 'worst'...","['place', 'terrible', 'people', 'charge', 'wor...",place terribl peopl charg worst part far yeah ...,place terrible people charge worst part far ye...,97
1,terrible service and they are saying that i ne...,1,"['terrible', 'service', 'saying', 'never', 'us...","['terribl', 'servic', 'say', 'never', 'use', '...","['terrible', 'service', 'saying', 'never', 'us...",terribl servic say never use servic lie call n...,terrible service saying never used service lie...,48
2,absolutely terrible company they sent me to co...,1,"['absolutely', 'terrible', 'company', 'sent', ...","['absolut', 'terribl', 'compani', 'sent', 'col...","['absolutely', 'terrible', 'company', 'sent', ...",absolut terribl compani sent collect without a...,absolutely terrible company sent collection wi...,211
3,to find it either park in front of the tuesday...,4,"['find', 'either', 'park', 'front', 'tuesday',...","['find', 'either', 'park', 'front', 'tuesday',...","['find', 'either', 'park', 'front', 'tuesday',...",find either park front tuesday morn mall entra...,find either park front tuesday morning mall en...,66
4,mall location used their services for sedan ni...,4,"['mall', 'location', 'used', 'services', 'seda...","['mall', 'locat', 'use', 'servic', 'sedan', 'n...","['mall', 'location', 'used', 'service', 'sedan...",mall locat use servic sedan nice perhap inform...,mall location used service sedan nice perhaps ...,28

In [6]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC
from sklearn.ensemble import RandomForestClassifier

In [10]:
train["text_lemma"] = train["text_lemma"].fillna("")
train["text_lemma"] = train["text_lemma"].astype(str)

train["text_stem"] = train["text_stem"].fillna("")
train["text_stem"] = train["text_stem"].astype(str)

train["text"] = train["text"].fillna("")
train["text"] = train["text"].astype(str)

X_d = train["text"]
X = train["text_lemma"]
x = train["text_stem"]
Y = train["rating"]

In [11]:
train.isnull().sum()

text             0
rating           0
tokens           0
stemmed          0
lemmatized       0
text_stem        0
text_lemma       0
review_length    0
dtype: int64

In [26]:
import pandas as pd
from sklearn.model_selection import GridSearchCV

def run_gridsearch(name, pipeline, params):
    # 1. Define multiple metrics
    scoring = {
        'Accuracy': 'accuracy',
        'MacroF1': 'f1_macro'
    }

    grid = GridSearchCV(
        pipeline,
        params,
        cv=3,
        n_jobs=-1,
        verbose=1,
        scoring=scoring,
        refit='MacroF1',
        return_train_score=False
    )

    grid.fit(X, Y)

    # 2. Extract detailed results into a table
    results_df = pd.DataFrame(grid.cv_results_)
    
    # Select columns for the 3 folds and the means
    columns_to_show = ['params']
    # Add Accuracy columns
    columns_to_show += ['split0_test_Accuracy', 'split1_test_Accuracy', 'split2_test_Accuracy', 'mean_test_Accuracy']
    # Add F1 columns
    columns_to_show += ['split0_test_MacroF1', 'split1_test_MacroF1', 'split2_test_MacroF1', 'mean_test_MacroF1']
    
    report_table = results_df[columns_to_show].sort_values('mean_test_MacroF1', ascending=False)

    print(f"\n==== {name} DETAILED FOLD RESULTS ====")
    print(report_table.to_string(index=False))

    # 3. Print the absolute bests
    best_f1_idx = results_df['mean_test_MacroF1'].idxmax()
    best_acc_idx = results_df['mean_test_Accuracy'].idxmax()

    print(f"\n--- {name} Summary ---")
    print(f"Best Params (for F1): {grid.best_params_}")
    print(f"Best Mean Macro-F1: {results_df.loc[best_f1_idx, 'mean_test_MacroF1']:.4f}")
    print(f"Best Mean Accuracy: {results_df.loc[best_acc_idx, 'mean_test_Accuracy']:.4f}")

    return grid

In [27]:
import joblib
from joblib import parallel_backend

nb_pipeline = Pipeline([
    ("tfidf", TfidfVectorizer()),
    ("clf", MultinomialNB())
])

nb_params = {
    "clf__alpha": [0.1, 0.5, 1.0],
    "tfidf__ngram_range": [(1, 1), (1, 2)],
    "tfidf__max_features": [10000, 20000, 50000]
}

with parallel_backend('threading'):
    nb_grid = run_gridsearch(
        "Naive Bayes",
        nb_pipeline,
        nb_params
    )

Fitting 3 folds for each of 18 candidates, totalling 54 fits

==== Naive Bayes DETAILED FOLD RESULTS ====
                                                                         params  split0_test_Accuracy  split1_test_Accuracy  split2_test_Accuracy  mean_test_Accuracy  split0_test_MacroF1  split1_test_MacroF1  split2_test_MacroF1  mean_test_MacroF1
{'clf__alpha': 0.1, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 2)}              0.637219              0.636490              0.635531            0.636413             0.465647             0.465948             0.465692           0.465763
{'clf__alpha': 0.1, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 2)}              0.635490              0.634865              0.634031            0.634795             0.455449             0.456240             0.457453           0.456381
{'clf__alpha': 0.5, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 2)}              0.635573              0.634500              0.634583            0.634885             0.445423             0.445651             0.448154           0.446409
{'clf__alpha': 0.1, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 2)}              0.632854              0.632146              0.631437            0.632146             0.445820             0.444637             0.446276           0.445577
{'clf__alpha': 0.5, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 2)}              0.636573              0.636625              0.635854            0.636351             0.439673             0.441473             0.441371           0.440839
{'clf__alpha': 0.5, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 2)}              0.632927              0.632094              0.631031            0.632017             0.440881             0.439504             0.440533           0.440306
{'clf__alpha': 1.0, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 2)}              0.631896              0.631344              0.630406            0.631215             0.432682             0.432268             0.433018           0.432656
{'clf__alpha': 1.0, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 2)}              0.634240              0.632927              0.633563            0.633576             0.430371             0.430254             0.432765           0.431130
{'clf__alpha': 0.1, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 1)}              0.619062              0.616781              0.616500            0.617448             0.416855             0.415051             0.415831           0.415913
{'clf__alpha': 0.1, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 1)}              0.620729              0.618469              0.618281            0.619160             0.414511             0.413304             0.413827           0.413881
{'clf__alpha': 0.1, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 1)}              0.615271              0.614135              0.612521            0.613976             0.411389             0.410384             0.409313           0.410362
{'clf__alpha': 0.5, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 1)}              0.620448              0.618500              0.618010            0.618986             0.408476             0.407876             0.408146           0.408166
{'clf__alpha': 1.0, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 2)}              0.632010              0.629823              0.629906            0.630580             0.405300             0.404131             0.404143           0.404525
{'clf__alpha': 0.5, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 1)}              0.617854              0.616833              0.615917            0.616868             0.400975             0.400758             0.401206           0.400980
{'clf__alpha': 1.0, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 1)}              0.618938              0.617302              0.617260            0.617833             0.399454             0.398902             0.400169           0.399509
{'clf__alpha': 1.0, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 1)}              0.612792              0.612625              0.611698            0.612372             0.378080             0.379572             0.379128           0.378927
{'clf__alpha': 0.5, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 1)}              0.609052              0.608615              0.606156            0.607941             0.365782             0.366203             0.363655           0.365214
{'clf__alpha': 1.0, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 1)}              0.598656              0.597427              0.596281            0.597455             0.325537             0.325276             0.323934           0.324916

--- Naive Bayes Summary ---
Best Params (for F1): {'clf__alpha': 0.1, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 2)}
Best Mean Macro-F1: 0.4658
Best Mean Accuracy: 0.6364

In [13]:
lr_pipeline = Pipeline([
    ("tfidf", TfidfVectorizer()),
    ("clf", LogisticRegression(max_iter=1000))
])

lr_params = {
    "clf__C": [0.5, 1, 3],
    "tfidf__ngram_range": [(1, 1), (1, 2)],
    "tfidf__max_features": [10000, 20000, 50000]
}

with parallel_backend('threading'):
    lr_grid = run_gridsearch(
        "Logistic Regression",
        lr_pipeline,
        lr_params
    )

Fitting 3 folds for each of 18 candidates, totalling 54 fits

==== Logistic Regression DETAILED FOLD RESULTS ====
                                                                     params  split0_test_Accuracy  split1_test_Accuracy  split2_test_Accuracy  mean_test_Accuracy  split0_test_MacroF1  split1_test_MacroF1  split2_test_MacroF1  mean_test_MacroF1
  {'clf__C': 3, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 2)}              0.648646              0.646969              0.647500            0.647705             0.510599             0.509157             0.512691           0.510815
  {'clf__C': 3, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 2)}              0.652115              0.649823              0.650417            0.650785             0.510937             0.508166             0.511990           0.510364
  {'clf__C': 3, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 2)}              0.646417              0.645062              0.646969            0.646149             0.508495             0.509119             0.512639           0.510084
  {'clf__C': 1, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 2)}              0.656479              0.654531              0.654573            0.655194             0.503690             0.501956             0.505089           0.503578
  {'clf__C': 1, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 2)}              0.657479              0.655146              0.654979            0.655868             0.503303             0.501909             0.504808           0.503340
  {'clf__C': 1, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 2)}              0.657813              0.655677              0.654865            0.656118             0.503920             0.501374             0.503513           0.502936
  {'clf__C': 3, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 1)}              0.646458              0.645094              0.644594            0.645382             0.498134             0.497215             0.499495           0.498281
  {'clf__C': 3, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 1)}              0.644938              0.643875              0.644115            0.644309             0.498493             0.496686             0.499366           0.498182
  {'clf__C': 3, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 1)}              0.644781              0.643635              0.643156            0.643858             0.497296             0.497313             0.498983           0.497864
{'clf__C': 0.5, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 2)}              0.657354              0.655906              0.654990            0.656083             0.494038             0.491530             0.495257           0.493608
{'clf__C': 0.5, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 2)}              0.658365              0.656563              0.655542            0.656823             0.494179             0.491136             0.493722           0.493012
  {'clf__C': 1, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 1)}              0.650927              0.649615              0.648948            0.649830             0.491104             0.490549             0.492908           0.491520
  {'clf__C': 1, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 1)}              0.650146              0.649344              0.649000            0.649497             0.491622             0.490336             0.492293           0.491417
  {'clf__C': 1, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 1)}              0.650375              0.649646              0.649188            0.649736             0.490088             0.490525             0.493519           0.491377
{'clf__C': 0.5, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 2)}              0.658125              0.655604              0.655583            0.656438             0.490555             0.487087             0.490823           0.489488
{'clf__C': 0.5, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 1)}              0.651323              0.650062              0.648823            0.650069             0.481976             0.480998             0.482113           0.481696
{'clf__C': 0.5, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 1)}              0.651427              0.650542              0.648875            0.650281             0.481390             0.481191             0.481287           0.481289
{'clf__C': 0.5, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 1)}              0.650958              0.650135              0.649375            0.650156             0.480959             0.480082             0.481935           0.480992

--- Logistic Regression Summary ---
Best Params (for F1): {'clf__C': 3, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 2)}
Best Mean Macro-F1: 0.5108
Best Mean Accuracy: 0.6568

In [14]:
svm_pipeline = Pipeline([
    ("tfidf", TfidfVectorizer(
    )),
    ("clf", LinearSVC())
])

svm_params = {
    "clf__C": [0.5, 1, 2],
    "tfidf__ngram_range": [(1, 1), (1, 2)],
    "tfidf__max_features": [10000, 20000, 50000]
}

with parallel_backend('threading'):
    svm_grid = run_gridsearch(
        "SVM",
        svm_pipeline,
        svm_params
    )

Fitting 3 folds for each of 18 candidates, totalling 54 fits

==== SVM DETAILED FOLD RESULTS ====
                                                                     params  split0_test_Accuracy  split1_test_Accuracy  split2_test_Accuracy  mean_test_Accuracy  split0_test_MacroF1  split1_test_MacroF1  split2_test_MacroF1  mean_test_MacroF1
  {'clf__C': 2, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 2)}              0.636656              0.635792              0.636021            0.636156             0.489737             0.489656             0.493750           0.491048
{'clf__C': 0.5, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 2)}              0.644813              0.643302              0.643271            0.643795             0.489780             0.489879             0.493298           0.490985
  {'clf__C': 1, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 2)}              0.632365              0.631375              0.631531            0.631757             0.489651             0.490111             0.493019           0.490927
  {'clf__C': 1, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 2)}              0.642333              0.641958              0.641667            0.641986             0.488913             0.489470             0.493420           0.490601
{'clf__C': 0.5, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 2)}              0.648646              0.647010              0.647396            0.647684             0.486773             0.487179             0.490865           0.488272
  {'clf__C': 2, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 2)}              0.616948              0.615688              0.617052            0.616563             0.485226             0.485969             0.488693           0.486629
  {'clf__C': 2, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 2)}              0.647687              0.645927              0.645990            0.646535             0.486132             0.483726             0.487738           0.485865
  {'clf__C': 1, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 2)}              0.649302              0.647594              0.647479            0.648125             0.484887             0.482755             0.486368           0.484670
{'clf__C': 0.5, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 2)}              0.651375              0.649719              0.649844            0.650313             0.482093             0.480555             0.484607           0.482418
  {'clf__C': 1, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 1)}              0.637156              0.633927              0.635406            0.635497             0.470163             0.467435             0.471358           0.469652
  {'clf__C': 2, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 1)}              0.633677              0.630177              0.631583            0.631812             0.470082             0.466524             0.471610           0.469405
  {'clf__C': 1, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 1)}              0.639563              0.635729              0.636760            0.637351             0.470277             0.466867             0.470861           0.469335
  {'clf__C': 2, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 1)}              0.629302              0.626604              0.627563            0.627823             0.469448             0.466742             0.470451           0.468880
{'clf__C': 0.5, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 1)}              0.643792              0.639760              0.641229            0.641594             0.468608             0.464825             0.469204           0.467546
{'clf__C': 0.5, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 1)}              0.644552              0.640771              0.641865            0.642396             0.468646             0.464573             0.469029           0.467416
  {'clf__C': 2, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 1)}              0.640333              0.636719              0.638219            0.638424             0.467540             0.465077             0.469257           0.467291
  {'clf__C': 1, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 1)}              0.642958              0.639292              0.640646            0.640965             0.467158             0.464566             0.468990           0.466905
{'clf__C': 0.5, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 1)}              0.645875              0.641448              0.642854            0.643392             0.466138             0.461999             0.467276           0.465138

--- SVM Summary ---
Best Params (for F1): {'clf__C': 2, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 2)}
Best Mean Macro-F1: 0.4910
Best Mean Accuracy: 0.6503

In [15]:
from sklearn.linear_model import SGDClassifier

sgd_pipeline = Pipeline([
    ("tfidf", TfidfVectorizer()), # Parameters handled by grid
    ("clf", SGDClassifier(max_iter=1000, tol=1e-3, random_state=25))
])


sgd_params = {
    "clf__alpha": [0.0001, 0.001, 0.01],
    "tfidf__ngram_range": [(1, 1), (1, 2)], 
    "tfidf__max_features": [10000,20000, 50000]
}

with parallel_backend('threading'):
    sgd_grid = run_gridsearch("SGD Classifier", sgd_pipeline, sgd_params)

Fitting 3 folds for each of 18 candidates, totalling 54 fits

==== SGD Classifier DETAILED FOLD RESULTS ====
                                                                            params  split0_test_Accuracy  split1_test_Accuracy  split2_test_Accuracy  mean_test_Accuracy  split0_test_MacroF1  split1_test_MacroF1  split2_test_MacroF1  mean_test_MacroF1
{'clf__alpha': 0.0001, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 2)}              0.635687              0.633729              0.633042            0.634153             0.403259             0.402127             0.403054           0.402813
{'clf__alpha': 0.0001, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 2)}              0.634667              0.632823              0.632656            0.633382             0.399555             0.399090             0.400321           0.399656
{'clf__alpha': 0.0001, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 1)}              0.633646              0.630354              0.630990            0.631663             0.399573             0.397721             0.399907           0.399067
{'clf__alpha': 0.0001, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 1)}              0.633062              0.630156              0.630604            0.631274             0.397773             0.396355             0.398700           0.397609
{'clf__alpha': 0.0001, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 1)}              0.632479              0.629667              0.629719            0.630622             0.396445             0.395405             0.396860           0.396237
{'clf__alpha': 0.0001, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 2)}              0.633292              0.631292              0.630865            0.631816             0.396397             0.395277             0.396479           0.396051
 {'clf__alpha': 0.001, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 2)}              0.594510              0.591865              0.592917            0.593097             0.333135             0.330743             0.331570           0.331816
 {'clf__alpha': 0.001, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 1)}              0.595417              0.592531              0.593021            0.593656             0.329854             0.328127             0.328653           0.328878
 {'clf__alpha': 0.001, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 2)}              0.590313              0.588333              0.589313            0.589319             0.327923             0.326357             0.326819           0.327033
 {'clf__alpha': 0.001, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 1)}              0.594562              0.591073              0.591917            0.592517             0.328565             0.325114             0.326378           0.326685
 {'clf__alpha': 0.001, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 1)}              0.593458              0.590500              0.591219            0.591726             0.325984             0.323622             0.324759           0.324788
 {'clf__alpha': 0.001, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 2)}              0.584979              0.583073              0.584052            0.584035             0.322538             0.321204             0.322364           0.322035
  {'clf__alpha': 0.01, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 2)}              0.571729              0.569104              0.569469            0.570101             0.308391             0.307156             0.307421           0.307656
  {'clf__alpha': 0.01, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 2)}              0.570958              0.567979              0.568958            0.569299             0.307766             0.305729             0.306579           0.306691
  {'clf__alpha': 0.01, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 2)}              0.569958              0.566583              0.568000            0.568181             0.306720             0.304309             0.305503           0.305511
  {'clf__alpha': 0.01, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 1)}              0.566500              0.562656              0.564219            0.564458             0.295936             0.292747             0.293887           0.294190
  {'clf__alpha': 0.01, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 1)}              0.567187              0.563760              0.564740            0.565229             0.295363             0.292582             0.293508           0.293818
  {'clf__alpha': 0.01, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 1)}              0.566948              0.563021              0.564469            0.564812             0.295551             0.292243             0.293432           0.293742

--- SGD Classifier Summary ---
Best Params (for F1): {'clf__alpha': 0.0001, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 2)}
Best Mean Macro-F1: 0.4028
Best Mean Accuracy: 0.6342

In [16]:
from sklearn.linear_model import RidgeClassifier

ridge_pipeline = Pipeline([
    ("tfidf", TfidfVectorizer()), 
    ("clf", RidgeClassifier(random_state=28))
])

ridge_params = {
    "tfidf__ngram_range": [(1, 1), (1, 2)],  # Comparison requirement [cite: 39]
    "tfidf__max_features": [10000,20000, 50000],   # Representation requirement [cite: 38]
    "clf__alpha": [0.1, 1.0, 10.0]           # The "knob" for regularization
}

with parallel_backend('threading'):
    ridge_grid = run_gridsearch("Ridge Classifier", ridge_pipeline, ridge_params)

Fitting 3 folds for each of 18 candidates, totalling 54 fits

==== Ridge Classifier DETAILED FOLD RESULTS ====
                                                                          params  split0_test_Accuracy  split1_test_Accuracy  split2_test_Accuracy  mean_test_Accuracy  split0_test_MacroF1  split1_test_MacroF1  split2_test_MacroF1  mean_test_MacroF1
 {'clf__alpha': 1.0, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 2)}              0.642333              0.640552              0.640708            0.641198             0.476529             0.475884             0.479256           0.477223
 {'clf__alpha': 0.1, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 2)}              0.637708              0.635792              0.637271            0.636924             0.473907             0.472687             0.478451           0.475015
 {'clf__alpha': 1.0, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 2)}              0.645969              0.643896              0.644719            0.644861             0.471287             0.470100             0.475388           0.472258
 {'clf__alpha': 0.1, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 2)}              0.609510              0.607906              0.608938            0.608785             0.469049             0.468492             0.473193           0.470245
 {'clf__alpha': 0.1, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 2)}              0.645177              0.643708              0.643240            0.644042             0.467634             0.465748             0.469433           0.467605
 {'clf__alpha': 1.0, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 2)}              0.647750              0.645760              0.645354            0.646288             0.465446             0.463398             0.467080           0.465308
 {'clf__alpha': 1.0, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 1)}              0.638365              0.635229              0.635333            0.636309             0.451298             0.448357             0.451321           0.450325
 {'clf__alpha': 1.0, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 1)}              0.638969              0.635323              0.636396            0.636896             0.450808             0.446890             0.451201           0.449633
 {'clf__alpha': 0.1, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 1)}              0.636427              0.633927              0.633979            0.634778             0.449452             0.447694             0.450241           0.449129
 {'clf__alpha': 0.1, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 1)}              0.626656              0.623313              0.623687            0.624552             0.450604             0.446912             0.449820           0.449112
{'clf__alpha': 10.0, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 2)}              0.650854              0.648542              0.649250            0.649549             0.448704             0.446147             0.452258           0.449037
{'clf__alpha': 10.0, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 2)}              0.651583              0.649500              0.649104            0.650062             0.448938             0.445682             0.449507           0.448042
 {'clf__alpha': 1.0, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 1)}              0.640792              0.637708              0.637948            0.638816             0.448470             0.445580             0.449217           0.447756
{'clf__alpha': 10.0, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 2)}              0.649177              0.647031              0.647094            0.647767             0.447482             0.445331             0.449296           0.447370
 {'clf__alpha': 0.1, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 1)}              0.614604              0.613240              0.613083            0.613642             0.446323             0.445124             0.446532           0.445993
{'clf__alpha': 10.0, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 1)}              0.644229              0.641083              0.641437            0.642250             0.434886             0.432024             0.435084           0.433998
{'clf__alpha': 10.0, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 1)}              0.644062              0.641906              0.641823            0.642597             0.433774             0.432199             0.434760           0.433577
{'clf__alpha': 10.0, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 1)}              0.644271              0.641708              0.641990            0.642656             0.433429             0.431675             0.434646           0.433250

--- Ridge Classifier Summary ---
Best Params (for F1): {'clf__alpha': 1.0, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 2)}
Best Mean Macro-F1: 0.4772
Best Mean Accuracy: 0.6501

In [17]:
import pandas as pd
from sklearn.model_selection import GridSearchCV

def run_gridsearch(name, pipeline, params):
    # 1. Define multiple metrics
    scoring = {
        'Accuracy': 'accuracy',
        'MacroF1': 'f1_macro'
    }

    grid_st = GridSearchCV(
        pipeline,
        params,
        cv=3,
        n_jobs=-1,
        verbose=1,
        scoring=scoring,
        refit='MacroF1',
        return_train_score=False
    )

    grid_st.fit(x, Y)

    # 2. Extract detailed results into a table
    results_df = pd.DataFrame(grid_st.cv_results_)
    
    # Select columns for the 3 folds and the means
    columns_to_show = ['params']
    # Add Accuracy columns
    columns_to_show += ['split0_test_Accuracy', 'split1_test_Accuracy', 'split2_test_Accuracy', 'mean_test_Accuracy']
    # Add F1 columns
    columns_to_show += ['split0_test_MacroF1', 'split1_test_MacroF1', 'split2_test_MacroF1', 'mean_test_MacroF1']
    
    report_table = results_df[columns_to_show].sort_values('mean_test_MacroF1', ascending=False)

    print(f"\n==== {name} DETAILED FOLD RESULTS ====")
    print(report_table.to_string(index=False))

    # 3. Print the absolute bests
    best_f1_idx = results_df['mean_test_MacroF1'].idxmax()
    best_acc_idx = results_df['mean_test_Accuracy'].idxmax()

    print(f"\n--- {name} Summary ---")
    print(f"Best Params (for F1): {grid_st.best_params_}")
    print(f"Best Mean Macro-F1: {results_df.loc[best_f1_idx, 'mean_test_MacroF1']:.4f}")
    print(f"Best Mean Accuracy: {results_df.loc[best_acc_idx, 'mean_test_Accuracy']:.4f}")

    return grid_st

In [18]:
import joblib
from joblib import parallel_backend

nb_pipeline = Pipeline([
    ("tfidf", TfidfVectorizer()),
    ("clf", MultinomialNB())
])

nb_params = {
    "clf__alpha": [0.1, 0.5, 1.0],
    "tfidf__ngram_range": [(1, 1), (1, 2)],
    "tfidf__max_features": [10000, 20000, 50000]
}

with parallel_backend('threading'):
    nb_grid = run_gridsearch(
        "Naive Bayes",
        nb_pipeline,
        nb_params
    )

Fitting 3 folds for each of 18 candidates, totalling 54 fits

==== Naive Bayes DETAILED FOLD RESULTS ====
                                                                         params  split0_test_Accuracy  split1_test_Accuracy  split2_test_Accuracy  mean_test_Accuracy  split0_test_MacroF1  split1_test_MacroF1  split2_test_MacroF1  mean_test_MacroF1
{'clf__alpha': 0.1, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 2)}              0.635104              0.634896              0.633302            0.634434             0.462244             0.462969             0.462135           0.462449
{'clf__alpha': 0.1, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 2)}              0.633677              0.633135              0.631708            0.632840             0.452543             0.454890             0.453445           0.453626
{'clf__alpha': 0.5, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 2)}              0.634208              0.633521              0.631927            0.633219             0.443532             0.445484             0.443797           0.444271
{'clf__alpha': 0.1, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 2)}              0.631042              0.631417              0.629510            0.630656             0.443206             0.443839             0.442969           0.443338
{'clf__alpha': 0.5, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 2)}              0.631115              0.631417              0.628979            0.630503             0.438542             0.439160             0.437451           0.438385
{'clf__alpha': 0.5, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 2)}              0.635031              0.634500              0.633729            0.634420             0.437169             0.438589             0.438248           0.438002
{'clf__alpha': 1.0, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 2)}              0.630313              0.630292              0.628375            0.629660             0.430826             0.430817             0.430176           0.430606
{'clf__alpha': 1.0, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 2)}              0.632333              0.631375              0.630031            0.631247             0.427538             0.428481             0.427675           0.427898
{'clf__alpha': 0.1, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 1)}              0.615771              0.614635              0.614406            0.614938             0.407927             0.406717             0.407688           0.407444
{'clf__alpha': 0.1, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 1)}              0.613448              0.611979              0.612021            0.612483             0.408973             0.406032             0.407324           0.407443
{'clf__alpha': 1.0, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 2)}              0.630135              0.628052              0.628229            0.628806             0.402288             0.402125             0.401732           0.402048
{'clf__alpha': 0.5, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 1)}              0.614906              0.614031              0.613969            0.614302             0.401261             0.399212             0.400976           0.400483
{'clf__alpha': 0.1, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 1)}              0.609260              0.608865              0.608208            0.608778             0.400868             0.399032             0.399094           0.399665
{'clf__alpha': 1.0, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 1)}              0.613135              0.612281              0.612062            0.612493             0.391364             0.389152             0.390630           0.390382
{'clf__alpha': 0.5, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 1)}              0.611073              0.611365              0.610802            0.611080             0.390158             0.389681             0.390351           0.390064
{'clf__alpha': 1.0, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 1)}              0.606271              0.606750              0.605781            0.606267             0.367069             0.368280             0.366821           0.367390
{'clf__alpha': 0.5, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 1)}              0.601781              0.602365              0.600469            0.601538             0.353426             0.354557             0.352029           0.353337
{'clf__alpha': 1.0, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 1)}              0.590625              0.591271              0.588260            0.590052             0.313202             0.315247             0.311504           0.313317

--- Naive Bayes Summary ---
Best Params (for F1): {'clf__alpha': 0.1, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 2)}
Best Mean Macro-F1: 0.4624
Best Mean Accuracy: 0.6344

In [19]:
lr_pipeline = Pipeline([
    ("tfidf", TfidfVectorizer()),
    ("clf", LogisticRegression(max_iter=1000))
])

lr_params = {
    "clf__C": [0.5, 1, 3],
    "tfidf__ngram_range": [(1, 1), (1, 2)],
    "tfidf__max_features": [10000, 20000, 50000]
}

with parallel_backend('threading'):
    lr_grid = run_gridsearch(
        "Logistic Regression",
        lr_pipeline,
        lr_params
    )

Fitting 3 folds for each of 18 candidates, totalling 54 fits

==== Logistic Regression DETAILED FOLD RESULTS ====
                                                                     params  split0_test_Accuracy  split1_test_Accuracy  split2_test_Accuracy  mean_test_Accuracy  split0_test_MacroF1  split1_test_MacroF1  split2_test_MacroF1  mean_test_MacroF1
  {'clf__C': 3, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 2)}              0.648010              0.647042              0.646698            0.647250             0.509235             0.509063             0.512284           0.510194
  {'clf__C': 3, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 2)}              0.650927              0.650792              0.649615            0.650444             0.509764             0.508159             0.511294           0.509739
  {'clf__C': 3, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 2)}              0.644167              0.644635              0.643698            0.644167             0.506709             0.508160             0.510112           0.508327
  {'clf__C': 1, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 2)}              0.655990              0.655635              0.655323            0.655649             0.502445             0.503029             0.507339           0.504271
  {'clf__C': 1, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 2)}              0.655667              0.655094              0.654667            0.655142             0.502297             0.501021             0.506173           0.503164
  {'clf__C': 1, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 2)}              0.655542              0.655438              0.654333            0.655104             0.501521             0.500690             0.502424           0.501545
  {'clf__C': 3, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 1)}              0.643042              0.643188              0.641385            0.642538             0.494762             0.495609             0.496261           0.495544
  {'clf__C': 3, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 1)}              0.644146              0.643906              0.642458            0.643503             0.494441             0.495207             0.496276           0.495308
  {'clf__C': 3, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 1)}              0.644927              0.644354              0.643281            0.644188             0.494358             0.494322             0.497027           0.495236
{'clf__C': 0.5, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 2)}              0.656990              0.655458              0.655917            0.656122             0.492663             0.490439             0.496636           0.493246
{'clf__C': 0.5, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 2)}              0.655521              0.655188              0.654979            0.655229             0.492202             0.491484             0.495892           0.493193
{'clf__C': 0.5, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 2)}              0.656469              0.654844              0.655271            0.655528             0.488298             0.487065             0.490865           0.488742
  {'clf__C': 1, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 1)}              0.648906              0.647958              0.647281            0.648049             0.488634             0.487799             0.489563           0.488665
  {'clf__C': 1, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 1)}              0.648604              0.647906              0.646708            0.647740             0.488609             0.487641             0.489465           0.488572
  {'clf__C': 1, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 1)}              0.648521              0.647510              0.646490            0.647507             0.489256             0.487958             0.488315           0.488510
{'clf__C': 0.5, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 1)}              0.649375              0.647510              0.648031            0.648306             0.480916             0.480791             0.482380           0.481362
{'clf__C': 0.5, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 1)}              0.649854              0.648073              0.647823            0.648583             0.481657             0.479628             0.481530           0.480938
{'clf__C': 0.5, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 1)}              0.649698              0.647938              0.647813            0.648483             0.480542             0.479118             0.482106           0.480589

--- Logistic Regression Summary ---
Best Params (for F1): {'clf__C': 3, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 2)}
Best Mean Macro-F1: 0.5102
Best Mean Accuracy: 0.6561

In [20]:
svm_pipeline = Pipeline([
    ("tfidf", TfidfVectorizer(
    )),
    ("clf", LinearSVC())
])

svm_params = {
    "clf__C": [0.5, 1, 2],
    "tfidf__ngram_range": [(1, 1), (1, 2)],
    "tfidf__max_features": [10000, 20000, 50000]
}

with parallel_backend('threading'):
    svm_grid = run_gridsearch(
        "SVM",
        svm_pipeline,
        svm_params
    )

Fitting 3 folds for each of 18 candidates, totalling 54 fits

==== SVM DETAILED FOLD RESULTS ====
                                                                     params  split0_test_Accuracy  split1_test_Accuracy  split2_test_Accuracy  mean_test_Accuracy  split0_test_MacroF1  split1_test_MacroF1  split2_test_MacroF1  mean_test_MacroF1
{'clf__C': 0.5, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 2)}              0.642458              0.641979              0.641698            0.642045             0.488456             0.488385             0.490384           0.489075
  {'clf__C': 1, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 2)}              0.641208              0.640437              0.640740            0.640795             0.487792             0.487575             0.491707           0.489024
  {'clf__C': 2, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 2)}              0.634854              0.633437              0.634781            0.634358             0.487628             0.486646             0.491429           0.488568
  {'clf__C': 1, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 2)}              0.629167              0.630031              0.628833            0.629344             0.487178             0.488608             0.489077           0.488288
{'clf__C': 0.5, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 2)}              0.647229              0.646552              0.646667            0.646816             0.485770             0.485578             0.489900           0.487083
  {'clf__C': 2, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 2)}              0.646740              0.645312              0.645229            0.645760             0.484835             0.482770             0.486676           0.484760
  {'clf__C': 2, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 2)}              0.614281              0.614990              0.614208            0.614493             0.482736             0.484576             0.484728           0.484013
  {'clf__C': 1, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 2)}              0.648604              0.647052              0.647156            0.647604             0.483430             0.482001             0.486072           0.483834
{'clf__C': 0.5, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 2)}              0.650781              0.648990              0.649208            0.649660             0.481343             0.478856             0.484440           0.481546
  {'clf__C': 1, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 1)}              0.636323              0.634646              0.634437            0.635135             0.464542             0.463521             0.466070           0.464711
  {'clf__C': 1, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 1)}              0.637885              0.635687              0.635427            0.636333             0.464870             0.463170             0.465827           0.464622
  {'clf__C': 2, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 1)}              0.632833              0.630125              0.630437            0.631132             0.464905             0.462500             0.466130           0.464512
  {'clf__C': 2, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 1)}              0.630073              0.628313              0.627667            0.628684             0.464219             0.463266             0.465498           0.464328
  {'clf__C': 2, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 1)}              0.638833              0.636375              0.635958            0.637056             0.464532             0.462032             0.465567           0.464044
  {'clf__C': 1, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 1)}              0.641094              0.638635              0.638365            0.639365             0.464011             0.461632             0.464734           0.463459
{'clf__C': 0.5, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 1)}              0.642490              0.639760              0.638708            0.640319             0.463807             0.461849             0.463284           0.462980
{'clf__C': 0.5, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 1)}              0.642344              0.640156              0.638958            0.640486             0.462694             0.461133             0.462877           0.462235
{'clf__C': 0.5, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 1)}              0.643885              0.640885              0.640385            0.641719             0.462356             0.459449             0.462269           0.461358

--- SVM Summary ---
Best Params (for F1): {'clf__C': 0.5, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 2)}
Best Mean Macro-F1: 0.4891
Best Mean Accuracy: 0.6497

In [21]:
from sklearn.linear_model import SGDClassifier

sgd_pipeline = Pipeline([
    ("tfidf", TfidfVectorizer()), # Parameters handled by grid
    ("clf", SGDClassifier(max_iter=1000, tol=1e-3, random_state=25))
])


sgd_params = {
    "clf__alpha": [0.0001, 0.001, 0.01],
    "tfidf__ngram_range": [(1, 1), (1, 2)], 
    "tfidf__max_features": [10000,20000, 50000]
}

with parallel_backend('threading'):
    sgd_grid = run_gridsearch("SGD Classifier", sgd_pipeline, sgd_params)

Fitting 3 folds for each of 18 candidates, totalling 54 fits

==== SGD Classifier DETAILED FOLD RESULTS ====
                                                                            params  split0_test_Accuracy  split1_test_Accuracy  split2_test_Accuracy  mean_test_Accuracy  split0_test_MacroF1  split1_test_MacroF1  split2_test_MacroF1  mean_test_MacroF1
{'clf__alpha': 0.0001, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 2)}              0.634062              0.633708              0.633646            0.633806             0.402792             0.402921             0.405125           0.403613
{'clf__alpha': 0.0001, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 2)}              0.633542              0.632656              0.632594            0.632931             0.399818             0.400024             0.401631           0.400491
{'clf__alpha': 0.0001, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 1)}              0.631469              0.629448              0.629792            0.630236             0.397889             0.397913             0.400330           0.398711
{'clf__alpha': 0.0001, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 1)}              0.631073              0.628990              0.629406            0.629823             0.396482             0.396579             0.399113           0.397391
{'clf__alpha': 0.0001, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 1)}              0.630875              0.628615              0.628958            0.629483             0.396089             0.396131             0.398066           0.396762
{'clf__alpha': 0.0001, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 2)}              0.631927              0.630812              0.630865            0.631201             0.395621             0.396106             0.397551           0.396426
 {'clf__alpha': 0.001, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 2)}              0.594479              0.592948              0.592646            0.593358             0.333996             0.332436             0.332147           0.332860
 {'clf__alpha': 0.001, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 1)}              0.595760              0.593656              0.593969            0.594462             0.331068             0.329495             0.329562           0.330042
 {'clf__alpha': 0.001, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 1)}              0.594917              0.592865              0.593135            0.593639             0.328526             0.327856             0.327618           0.328000
 {'clf__alpha': 0.001, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 2)}              0.590552              0.588698              0.589625            0.589625             0.328716             0.327426             0.327733           0.327958
 {'clf__alpha': 0.001, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 1)}              0.594448              0.592313              0.592417            0.593059             0.327542             0.326565             0.326017           0.326708
 {'clf__alpha': 0.001, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 2)}              0.584906              0.583875              0.584219            0.584333             0.322888             0.322699             0.322754           0.322780
  {'clf__alpha': 0.01, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 2)}              0.570094              0.567708              0.567865            0.568556             0.307837             0.306904             0.307146           0.307296
  {'clf__alpha': 0.01, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 2)}              0.568802              0.566448              0.567000            0.567417             0.306659             0.304933             0.305721           0.305771
  {'clf__alpha': 0.01, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 2)}              0.567729              0.564792              0.565906            0.566142             0.305540             0.303798             0.304423           0.304587
  {'clf__alpha': 0.01, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 1)}              0.563594              0.560115              0.561187            0.561632             0.292958             0.290205             0.290784           0.291315
  {'clf__alpha': 0.01, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 1)}              0.564458              0.561115              0.561969            0.562514             0.293131             0.289779             0.290760           0.291223
  {'clf__alpha': 0.01, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 1)}              0.564031              0.560333              0.561229            0.561865             0.292834             0.289569             0.290005           0.290803

--- SGD Classifier Summary ---
Best Params (for F1): {'clf__alpha': 0.0001, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 2)}
Best Mean Macro-F1: 0.4036
Best Mean Accuracy: 0.6338

In [22]:
from sklearn.linear_model import RidgeClassifier

ridge_pipeline = Pipeline([
    ("tfidf", TfidfVectorizer()), 
    ("clf", RidgeClassifier(random_state=28))
])

ridge_params = {
    "tfidf__ngram_range": [(1, 1), (1, 2)],  # Comparison requirement [cite: 39]
    "tfidf__max_features": [10000,20000, 50000],   # Representation requirement [cite: 38]
    "clf__alpha": [0.1, 1.0, 10.0]           # The "knob" for regularization
}

with parallel_backend('threading'):
    ridge_grid = run_gridsearch("Ridge Classifier", ridge_pipeline, ridge_params)

Fitting 3 folds for each of 18 candidates, totalling 54 fits

==== Ridge Classifier DETAILED FOLD RESULTS ====
                                                                          params  split0_test_Accuracy  split1_test_Accuracy  split2_test_Accuracy  mean_test_Accuracy  split0_test_MacroF1  split1_test_MacroF1  split2_test_MacroF1  mean_test_MacroF1
 {'clf__alpha': 1.0, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 2)}              0.639760              0.638823              0.639448            0.639344             0.474423             0.473702             0.477432           0.475186
 {'clf__alpha': 0.1, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 2)}              0.637323              0.634927              0.636156            0.636135             0.473857             0.471603             0.477052           0.474171
 {'clf__alpha': 1.0, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 2)}              0.645250              0.643583              0.644552            0.644462             0.470398             0.468749             0.474968           0.471372
 {'clf__alpha': 0.1, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 2)}              0.607031              0.606896              0.606802            0.606910             0.467727             0.468974             0.470271           0.468991
 {'clf__alpha': 0.1, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 2)}              0.644813              0.642698              0.642563            0.643358             0.467864             0.464356             0.468452           0.466891
 {'clf__alpha': 1.0, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 2)}              0.646781              0.644646              0.644948            0.645458             0.464449             0.461148             0.466215           0.463937
{'clf__alpha': 10.0, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 2)}              0.648896              0.647010              0.648125            0.648010             0.446755             0.444433             0.450758           0.447315
{'clf__alpha': 10.0, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 2)}              0.649917              0.648594              0.648438            0.648983             0.446503             0.445450             0.449354           0.447103
{'clf__alpha': 10.0, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 2)}              0.647865              0.645813              0.646531            0.646736             0.446656             0.443557             0.448673           0.446295
 {'clf__alpha': 0.1, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 1)}              0.634333              0.632333              0.630854            0.632507             0.446773             0.445019             0.445705           0.445833
 {'clf__alpha': 1.0, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 1)}              0.636917              0.634042              0.632552            0.634503             0.446753             0.444612             0.444590           0.445318
 {'clf__alpha': 1.0, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 1)}              0.637490              0.634177              0.633667            0.635111             0.446256             0.443636             0.445092           0.444995
 {'clf__alpha': 1.0, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 1)}              0.639177              0.636260              0.634979            0.636806             0.446088             0.442938             0.444422           0.444483
 {'clf__alpha': 0.1, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 1)}              0.624719              0.621823              0.621458            0.622667             0.444597             0.442663             0.443818           0.443693
 {'clf__alpha': 0.1, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 1)}              0.615833              0.615031              0.613021            0.614628             0.441323             0.441171             0.440020           0.440838
{'clf__alpha': 10.0, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 1)}              0.642448              0.640010              0.638563            0.640340             0.432046             0.430555             0.430910           0.431170
{'clf__alpha': 10.0, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 1)}              0.642469              0.640115              0.638833            0.640472             0.431710             0.429996             0.430903           0.430869
{'clf__alpha': 10.0, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 1)}              0.642469              0.640188              0.638906            0.640521             0.431707             0.430045             0.430775           0.430842

--- Ridge Classifier Summary ---
Best Params (for F1): {'clf__alpha': 1.0, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 2)}
Best Mean Macro-F1: 0.4752
Best Mean Accuracy: 0.6490

# Deep-Learning Model

In [23]:
train['rating'] = train['rating'] - 1

In [25]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

# Use the ORIGINAL review text here, not stemmed/lemmatized!
max_words = 10000
max_len = 100 # Max words per review

tokenizer = Tokenizer(num_words=max_words)
tokenizer.fit_on_texts(train['text']) # Assuming 'text' is your raw column

sequences = tokenizer.texts_to_sequences(train['text'])
X_seq = pad_sequences(sequences, maxlen=max_len)
y_seq = train['rating'].values # Use the 0-4 labels you fixed earlier

In [ ]:
import pandas as pd
from sklearn.model_selection import GridSearchCV
import joblib
from joblib import parallel_backend

def run_gridsearch(name, pipeline, params):
    # 1. Define multiple metrics
    scoring = {
        'Accuracy': 'accuracy',
        'MacroF1': 'f1_macro'
    }

    grid = GridSearchCV(
        pipeline,
        params,
        cv=3,
        n_jobs=1,
        verbose=1,
        scoring=scoring,
        refit='MacroF1',
        return_train_score=False
    )

    # Use a context manager to ensure it doesn't fork
    with parallel_backend('threading'):
        grid.fit(X_seq, y_seq)

    # 2. Extract detailed results into a table
    results_df = pd.DataFrame(grid.cv_results_)

    # Select columns for the 3 folds and the means
    columns_to_show = ['params']
    # Add Accuracy columns
    columns_to_show += ['split0_test_Accuracy', 'split1_test_Accuracy', 'split2_test_Accuracy', 'mean_test_Accuracy']
    # Add F1 columns
    columns_to_show += ['split0_test_MacroF1', 'split1_test_MacroF1', 'split2_test_MacroF1', 'mean_test_MacroF1']

    report_table = results_df[columns_to_show].sort_values('mean_test_MacroF1', ascending=False)

    print(f"\n==== {name} DETAILED FOLD RESULTS ====")
    print(report_table.to_string(index=False))

    # 3. Print the absolute bests
    best_f1_idx = results_df['mean_test_MacroF1'].idxmax()
    best_acc_idx = results_df['mean_test_Accuracy'].idxmax()

    print(f"\n--- {name} Summary ---")
    print(f"Best Params (for F1): {grid.best_params_}")
    print(f"Best Mean Macro-F1: {results_df.loc[best_f1_idx, 'mean_test_MacroF1']:.4f}")
    print(f"Best Mean Accuracy: {results_df.loc[best_acc_idx, 'mean_test_Accuracy']:.4f}")

    return grid

In [ ]:
!pip uninstall -y scikit-learn
!pip install scikit-learn==1.5.2

Found existing installation: scikit-learn 1.5.2
Uninstalling scikit-learn-1.5.2:
  Successfully uninstalled scikit-learn-1.5.2
Defaulting to user installation because normal site-packages is not writeable
Collecting scikit-learn==1.5.2
  Using cached scikit_learn-1.5.2-cp313-cp313-win_amd64.whl.metadata (13 kB)
Requirement already satisfied: numpy>=1.19.5 in c:\users\hafee\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from scikit-learn==1.5.2) (2.2.4)
Requirement already satisfied: scipy>=1.6.0 in c:\users\hafee\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from scikit-learn==1.5.2) (1.15.2)
Requirement already satisfied: joblib>=1.2.0 in c:\users\hafee\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from scikit-learn==1.5.2) (1.5.0)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\hafee\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from scikit-learn==1.5.2) (3.6.0)
Using cached scikit_learn-1.5.2-cp313-cp313-win_amd64.whl (11.0 MB)
Installing collected packages: scikit-learn
Successfully installed scikit-learn-1.5.2

[notice] A new release of pip is available: 25.1.1 -> 26.0.1
[notice] To update, run: C:\Users\hafee\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Bidirectional, LSTM, Dense, Dropout, Input


# Force everything to run in the current thread
parallel_backend('threading')

# Pass max_len and max_words as defaults so the function is self-contained
def create_bilstm_model(lstm_units=64, dropout_rate=0.2, embedding_dim=100, max_len=100, max_words=10000):
    model = Sequential([
        Input(shape=(max_len,)), 

        Embedding(
            input_dim=max_words,
            output_dim=embedding_dim
        ),

        Bidirectional(LSTM(lstm_units)),
        Dropout(dropout_rate),
        Dense(32, activation="relu"),
        Dense(5, activation="softmax")
    ])

    model.compile(
        optimizer="adam",
        loss="sparse_categorical_crossentropy",
        metrics=["accuracy"]
    )

    return model

from scikeras.wrappers import KerasClassifier

# Wrap for Scikit-Learn
bilstm_clf = KerasClassifier(
    model=create_bilstm_model,
    model__max_len=max_len,     # Explicitly pass these
    model__max_words=max_words, # Explicitly pass these
    verbose=0
)

# Parameters to tune for your "Critical Analysis" [cite: 70]
bilstm_params = {
    "model__lstm_units": [32, 64, 128],
    "model__embedding_dim": [100, 200],
    "batch_size": [64],
    "epochs": [5]
}

bilstm_grid = run_gridsearch("BiLSTM", bilstm_clf, bilstm_params)

Fitting 3 folds for each of 6 candidates, totalling 18 fits

==== BiLSTM DETAILED FOLD RESULTS ====
                                                                                params  split0_test_Accuracy  split1_test_Accuracy  split2_test_Accuracy  mean_test_Accuracy  split0_test_MacroF1  split1_test_MacroF1  split2_test_MacroF1  mean_test_MacroF1
{'batch_size': 64, 'epochs': 5, 'model__embedding_dim': 200, 'model__lstm_units': 128}              0.654979              0.654677              0.651177            0.653611             0.528028             0.539777             0.539956           0.535920
 {'batch_size': 64, 'epochs': 5, 'model__embedding_dim': 100, 'model__lstm_units': 32}              0.657760              0.652635              0.647823            0.652740             0.529127             0.533680             0.542673           0.535160
 {'batch_size': 64, 'epochs': 5, 'model__embedding_dim': 200, 'model__lstm_units': 32}              0.653292              0.654385              0.655375            0.654351             0.534379             0.533417             0.529596           0.532464
 {'batch_size': 64, 'epochs': 5, 'model__embedding_dim': 100, 'model__lstm_units': 64}              0.657781              0.653000              0.662719            0.657833             0.537887             0.539730             0.519213           0.532277
 {'batch_size': 64, 'epochs': 5, 'model__embedding_dim': 200, 'model__lstm_units': 64}              0.655052              0.649958              0.657937            0.654316             0.526861             0.536938             0.531570           0.531790
{'batch_size': 64, 'epochs': 5, 'model__embedding_dim': 100, 'model__lstm_units': 128}              0.659188              0.660719              0.659250            0.659719             0.526618             0.530108             0.537338           0.531355

--- BiLSTM Summary ---
Best Params (for F1): {'batch_size': 64, 'epochs': 5, 'model__embedding_dim': 200, 'model__lstm_units': 128}
Best Mean Macro-F1: 0.5359
Best Mean Accuracy: 0.6597

In [ ]:
from tensorflow.keras.layers import SpatialDropout1D, Bidirectional, LSTM, BatchNormalization
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Bidirectional, LSTM, Dense, Dropout, Input, SpatialDropout1D, BatchNormalization
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau
from sklearn.utils import class_weight
import numpy as np

def build_advanced_bilstm():
    model = Sequential([
        Input(shape=(max_len,)),
        # Increase embedding_dim to 300 if using GloVe 300d
        Embedding(input_dim=max_words, output_dim=100, mask_zero=True), 
        SpatialDropout1D(0.3),
        
        Bidirectional(LSTM(128, return_sequences=True)), # Stacked LSTM
        Bidirectional(LSTM(64)),
        
        BatchNormalization(), # Stabilizes learning
        Dropout(0.5),
        Dense(64, activation='relu'),
        Dense(5, activation='softmax')
    ])
    
    model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
    return model

# Add Callbacks to prevent the 58-minute timeout/overfit cycle
callbacks = [
    EarlyStopping(monitor='val_loss', patience=3, restore_best_weights=True),
    ReduceLROnPlateau(monitor='val_loss', factor=0.2, patience=2)
]

# Train with Class Weights (Calculated from your y_seq)
from sklearn.utils import class_weight
import numpy as np

weights = class_weight.compute_class_weight('balanced', classes=np.unique(y_seq), y=y_seq)
class_weights_dict = dict(enumerate(weights))

model = build_advanced_bilstm()
history = model.fit(
    X_seq, y_seq,
    validation_split=0.2,
    epochs=15, # Callbacks will stop it early if it overfits
    batch_size=32, # Smaller batch size often helps accuracy
    class_weight=class_weights_dict,
    callbacks=callbacks
)

Epoch 1/15
7200/7200 ━━━━━━━━━━━━━━━━━━━━ 909s 126ms/step - accuracy: 0.5467 - loss: 1.0815 - val_accuracy: 0.5782 - val_loss: 0.9612 - learning_rate: 0.0010
Epoch 2/15
7200/7200 ━━━━━━━━━━━━━━━━━━━━ 976s 136ms/step - accuracy: 0.5949 - loss: 0.9766 - val_accuracy: 0.6030 - val_loss: 0.9317 - learning_rate: 0.0010
Epoch 3/15
7200/7200 ━━━━━━━━━━━━━━━━━━━━ 1061s 147ms/step - accuracy: 0.6139 - loss: 0.9294 - val_accuracy: 0.5886 - val_loss: 0.9498 - learning_rate: 0.0010
Epoch 4/15
7200/7200 ━━━━━━━━━━━━━━━━━━━━ 1212s 168ms/step - accuracy: 0.6309 - loss: 0.8938 - val_accuracy: 0.6245 - val_loss: 0.9112 - learning_rate: 0.0010
Epoch 5/15
7200/7200 ━━━━━━━━━━━━━━━━━━━━ 3725s 517ms/step - accuracy: 0.6452 - loss: 0.8623 - val_accuracy: 0.5877 - val_loss: 0.9621 - learning_rate: 0.0010
Epoch 6/15
7200/7200 ━━━━━━━━━━━━━━━━━━━━ 28646s 4s/step - accuracy: 0.6588 - loss: 0.8304 - val_accuracy: 0.5905 - val_loss: 0.9667 - learning_rate: 0.0010
Epoch 7/15
7200/7200 ━━━━━━━━━━━━━━━━━━━━ 907s 126ms/step - accuracy: 0.6906 - loss: 0.7580 - val_accuracy: 0.6116 - val_loss: 0.9761 - learning_rate: 2.0000e-04

# BERT

In [29]:
# Install required libraries if not already present
%pip install transformers[torch] datasets accelerate scikit-learn

Defaulting to user installation because normal site-packages is not writeable
Collecting datasets
  Using cached datasets-4.8.4-py3-none-any.whl.metadata (19 kB)
Collecting accelerate
  Using cached accelerate-1.13.0-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: scikit-learn in c:\users\hafee\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (1.5.2)
Collecting transformers[torch]
  Using cached transformers-5.3.0-py3-none-any.whl.metadata (32 kB)
Collecting huggingface-hub<2.0,>=1.3.0 (from transformers[torch])
  Using cached huggingface_hub-1.7.2-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: numpy>=1.17 in c:\users\hafee\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from transformers[torch]) (2.2.4)
Requirement already satisfied: packaging>=20.0 in c:\users\hafee\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from transformers[torch]) (24.2)
Requirement already satisfied: pyyaml>=5.1 in c:\users\hafee\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from transformers[torch]) (6.0.2)
Requirement already satisfied: regex!=2019.12.17 in c:\users\hafee\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from transformers[torch]) (2026.2.28)
Collecting tokenizers<=0.23.0,>=0.22.0 (from transformers[torch])
  Using cached tokenizers-0.22.2-cp39-abi3-win_amd64.whl.metadata (7.4 kB)
Collecting typer (from transformers[torch])
  Using cached typer-0.24.1-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: safetensors>=0.4.3 in c:\users\hafee\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from transformers[torch]) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in c:\users\hafee\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from transformers[torch]) (4.67.3)
Collecting torch>=2.4 (from transformers[torch])
  Using cached torch-2.11.0-cp313-cp313-win_amd64.whl.metadata (29 kB)
Collecting filelock>=3.10.0 (from huggingface-hub<2.0,>=1.3.0->transformers[torch])
  Using cached filelock-3.25.2-py3-none-any.whl.metadata (2.0 kB)
Collecting fsspec>=2023.5.0 (from huggingface-hub<2.0,>=1.3.0->transformers[torch])
  Using cached fsspec-2026.2.0-py3-none-any.whl.metadata (10 kB)
Collecting hf-xet<2.0.0,>=1.4.2 (from huggingface-hub<2.0,>=1.3.0->transformers[torch])
  Using cached hf_xet-1.4.2-cp37-abi3-win_amd64.whl.metadata (4.9 kB)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\users\hafee\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from huggingface-hub<2.0,>=1.3.0->transformers[torch]) (0.28.1)
Requirement already satisfied: typing-extensions>=4.1.0 in c:\users\hafee\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from huggingface-hub<2.0,>=1.3.0->transformers[torch]) (4.15.0)
Requirement already satisfied: anyio in c:\users\hafee\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers[torch]) (4.9.0)
Requirement already satisfied: certifi in c:\users\hafee\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers[torch]) (2026.2.25)
Requirement already satisfied: httpcore==1.* in c:\users\hafee\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers[torch]) (1.0.9)
Requirement already satisfied: idna in c:\users\hafee\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers[torch]) (3.10)
Requirement already satisfied: h11>=0.16 in c:\users\hafee\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers[torch]) (0.16.0)
Requirement already satisfied: pyarrow>=21.0.0 in c:\users\hafee\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from datasets) (23.0.1)
Collecting dill<0.4.2,>=0.3.0 (from datasets)
  Using cached dill-0.4.1-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: pandas in c:\users\hafee\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from datasets) (2.2.3)
Requirement already satisfied: requests>=2.32.2 in c:\users\hafee\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from datasets) (2.32.3)
Requirement already satisfied: xxhash in c:\users\hafee\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from datasets) (3.6.0)
Collecting multiprocess<0.70.20 (from datasets)
  Using cached multiprocess-0.70.19-py313-none-any.whl.metadata (7.5 kB)
Collecting aiohttp!=4.0.0a0,!=4.0.0a1 (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Using cached aiohttp-3.13.3-cp313-cp313-win_amd64.whl.metadata (8.4 kB)
Requirement already satisfied: psutil in c:\users\hafee\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from accelerate) (7.0.0)
Requirement already satisfied: scipy>=1.6.0 in c:\users\hafee\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from scikit-learn) (1.15.2)
Requirement already satisfied: joblib>=1.2.0 in c:\users\hafee\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from scikit-learn) (1.5.0)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\hafee\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from scikit-learn) (3.6.0)
Collecting aiohappyeyeballs>=2.5.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Using cached aiohappyeyeballs-2.6.1-py3-none-any.whl.metadata (5.9 kB)
Collecting aiosignal>=1.4.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Using cached aiosignal-1.4.0-py3-none-any.whl.metadata (3.7 kB)
Requirement already satisfied: attrs>=17.3.0 in c:\users\hafee\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (25.3.0)
Collecting frozenlist>=1.1.1 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Using cached frozenlist-1.8.0-cp313-cp313-win_amd64.whl.metadata (21 kB)
Collecting multidict<7.0,>=4.5 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Using cached multidict-6.7.1-cp313-cp313-win_amd64.whl.metadata (5.5 kB)
Requirement already satisfied: propcache>=0.2.0 in c:\users\hafee\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (0.4.1)
Collecting yarl<2.0,>=1.17.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Using cached yarl-1.23.0-cp313-cp313-win_amd64.whl.metadata (82 kB)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\hafee\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from requests>=2.32.2->datasets) (3.4.1)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\hafee\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from requests>=2.32.2->datasets) (2.6.3)
Requirement already satisfied: setuptools<82 in c:\users\hafee\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from torch>=2.4->transformers[torch]) (80.3.1)
Requirement already satisfied: sympy>=1.13.3 in c:\users\hafee\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from torch>=2.4->transformers[torch]) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in c:\users\hafee\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from torch>=2.4->transformers[torch]) (3.6.1)
Requirement already satisfied: jinja2 in c:\users\hafee\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from torch>=2.4->transformers[torch]) (3.1.6)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\hafee\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from sympy>=1.13.3->torch>=2.4->transformers[torch]) (1.3.0)
Requirement already satisfied: colorama in c:\users\hafee\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from tqdm>=4.27->transformers[torch]) (0.4.6)
Requirement already satisfied: sniffio>=1.1 in c:\users\hafee\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from anyio->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers[torch]) (1.3.1)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\hafee\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from jinja2->torch>=2.4->transformers[torch]) (3.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\hafee\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\hafee\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from pandas->datasets) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\hafee\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from pandas->datasets) (2025.1)
Requirement already satisfied: six>=1.5 in c:\users\hafee\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Collecting click>=8.2.1 (from typer->transformers[torch])
  Using cached click-8.3.1-py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: shellingham>=1.3.0 in c:\users\hafee\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from typer->transformers[torch]) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in c:\users\hafee\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from typer->transformers[torch]) (14.1.0)
Collecting annotated-doc>=0.0.2 (from typer->transformers[torch])
  Using cached annotated_doc-0.0.4-py3-none-any.whl.metadata (6.6 kB)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\hafee\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from rich>=12.3.0->typer->transformers[torch]) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\hafee\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from rich>=12.3.0->typer->transformers[torch]) (2.19.1)
Requirement already satisfied: mdurl~=0.1 in c:\users\hafee\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->transformers[torch]) (0.1.2)
Using cached transformers-5.3.0-py3-none-any.whl (10.7 MB)
Using cached huggingface_hub-1.7.2-py3-none-any.whl (618 kB)
Using cached hf_xet-1.4.2-cp37-abi3-win_amd64.whl (3.7 MB)
Using cached tokenizers-0.22.2-cp39-abi3-win_amd64.whl (2.7 MB)
Using cached datasets-4.8.4-py3-none-any.whl (526 kB)
Using cached dill-0.4.1-py3-none-any.whl (120 kB)
Using cached fsspec-2026.2.0-py3-none-any.whl (202 kB)
Using cached multiprocess-0.70.19-py313-none-any.whl (156 kB)
Using cached accelerate-1.13.0-py3-none-any.whl (383 kB)
Using cached aiohttp-3.13.3-cp313-cp313-win_amd64.whl (453 kB)
Using cached multidict-6.7.1-cp313-cp313-win_amd64.whl (45 kB)
Using cached yarl-1.23.0-cp313-cp313-win_amd64.whl (87 kB)
Using cached aiohappyeyeballs-2.6.1-py3-none-any.whl (15 kB)
Using cached aiosignal-1.4.0-py3-none-any.whl (7.5 kB)
Using cached filelock-3.25.2-py3-none-any.whl (26 kB)
Using cached frozenlist-1.8.0-cp313-cp313-win_amd64.whl (43 kB)
Using cached torch-2.11.0-cp313-cp313-win_amd64.whl (114.6 MB)
Using cached typer-0.24.1-py3-none-any.whl (56 kB)
Using cached annotated_doc-0.0.4-py3-none-any.whl (5.3 kB)
Using cached click-8.3.1-py3-none-any.whl (108 kB)
Installing collected packages: multidict, hf-xet, fsspec, frozenlist, filelock, dill, click, annotated-doc, aiohappyeyeballs, yarl, torch, multiprocess, aiosignal, typer, aiohttp, huggingface-hub, tokenizers, datasets, accelerate, transformers

   -- -------------------------------------  1/20 [hf-xet]
   ---- -----------------------------------  2/20 [fsspec]
   ---- -----------------------------------  2/20 [fsspec]
   ---- -----------------------------------  2/20 [fsspec]
   ---- -----------------------------------  2/20 [fsspec]
   ---- -----------------------------------  2/20 [fsspec]
   ---- -----------------------------------  2/20 [fsspec]
   ---- -----------------------------------  2/20 [fsspec]
   ------ ---------------------------------  3/20 [frozenlist]
   -------- -------------------------------  4/20 [filelock]
   ---------- -----------------------------  5/20 [dill]
   ---------- -----------------------------  5/20 [dill]
   ---------- -----------------------------  5/20 [dill]
   ---------- -----------------------------  5/20 [dill]
   ---------- -----------------------------  5/20 [dill]
   ---------- -----------------------------  5/20 [dill]
  Attempting uninstall: click
   ---------- -----------------------------  5/20 [dill]
    Found existing installation: click 8.1.8
   ---------- -----------------------------  5/20 [dill]
    Uninstalling click-8.1.8:
   ---------- -----------------------------  5/20 [dill]
      Successfully uninstalled click-8.1.8
   ---------- -----------------------------  5/20 [dill]
   ------------ ---------------------------  6/20 [click]
   ------------ ---------------------------  6/20 [click]
   ------------ ---------------------------  6/20 [click]
   ---------------- -----------------------  8/20 [aiohappyeyeballs]
   ------------------ ---------------------  9/20 [yarl]
   -------------------- ------------------- 10/20 [torch]
   -------------------- ------------------- 10/20 [torch]
   -------------------- ------------------- 10/20 [torch]
   -------------------- ------------------- 10/20 [torch]
   -------------------- ------------------- 10/20 [torch]
   -------------------- ------------------- 10/20 [torch]
   -------------------- ------------------- 10/20 [torch]
   -------------------- ------------------- 10/20 [torch]
   -------------------- ------------------- 10/20 [torch]
   -------------------- ------------------- 10/20 [torch]
   -------------------- ------------------- 10/20 [torch]
   -------------------- ------------------- 10/20 [torch]
   -------------------- ------------------- 10/20 [torch]
   -------------------- ------------------- 10/20 [torch]
   -------------------- ------------------- 10/20 [torch]
   -------------------- ------------------- 10/20 [torch]
   -------------------- ------------------- 10/20 [torch]
   -------------------- ------------------- 10/20 [torch]
   -------------------- ------------------- 10/20 [torch]
   -------------------- ------------------- 10/20 [torch]
   -------------------- ------------------- 10/20 [torch]
   -------------------- ------------------- 10/20 [torch]
   -------------------- ------------------- 10/20 [torch]
   -------------------- ------------------- 10/20 [torch]
   -------------------- ------------------- 10/20 [torch]
   -------------------- ------------------- 10/20 [torch]
   -------------------- ------------------- 10/20 [torch]
   -------------------- ------------------- 10/20 [torch]
   -------------------- ------------------- 10/20 [torch]
   -------------------- ------------------- 10/20 [torch]
   -------------------- ------------------- 10/20 [torch]
   -------------------- ------------------- 10/20 [torch]
   -------------------- ------------------- 10/20 [torch]
   -------------------- ------------------- 10/20 [torch]
   -------------------- ------------------- 10/20 [torch]
   -------------------- ------------------- 10/20 [torch]
   -------------------- ------------------- 10/20 [torch]
   -------------------- ------------------- 10/20 [torch]
   -------------------- ------------------- 10/20 [torch]
   -------------------- ------------------- 10/20 [torch]
   -------------------- ------------------- 10/20 [torch]
   -------------------- ------------------- 10/20 [torch]
   -------------------- ------------------- 10/20 [torch]
   -------------------- ------------------- 10/20 [torch]
   -------------------- ------------------- 10/20 [torch]
   -------------------- ------------------- 10/20 [torch]
   -------------------- ------------------- 10/20 [torch]
   -------------------- ------------------- 10/20 [torch]
   -------------------- ------------------- 10/20 [torch]
   -------------------- ------------------- 10/20 [torch]
   -------------------- ------------------- 10/20 [torch]
   -------------------- ------------------- 10/20 [torch]
   -------------------- ------------------- 10/20 [torch]
   -------------------- ------------------- 10/20 [torch]
   -------------------- ------------------- 10/20 [torch]
   -------------------- ------------------- 10/20 [torch]
   -------------------- ------------------- 10/20 [torch]
   -------------------- ------------------- 10/20 [torch]
   -------------------- ------------------- 10/20 [torch]
   -------------------- ------------------- 10/20 [torch]
   -------------------- ------------------- 10/20 [torch]
   -------------------- ------------------- 10/20 [torch]
   -------------------- ------------------- 10/20 [torch]
   -------------------- ------------------- 10/20 [torch]
   -------------------- ------------------- 10/20 [torch]
   -------------------- ------------------- 10/20 [torch]
   -------------------- ------------------- 10/20 [torch]

[notice] A new release of pip is available: 25.1.1 -> 26.0.1
[notice] To update, run: C:\Users\hafee\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [30]:
import torch
import pandas as pd
import numpy as np
from datasets import Dataset
from transformers import (
    DistilBertTokenizerFast, 
    DistilBertForSequenceClassification, 
    Trainer, 
    TrainingArguments
)
from sklearn.utils.class_weight import compute_class_weight
from sklearn.metrics import accuracy_score, f1_score
from torch import nn

# Verify GPU availability
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Working on: {device}")

Working on: cpu

In [31]:
# Load full dataset
train = pd.read_csv("train_processed.csv")
train['text'] = train['text'].fillna('').astype(str)

# Shift ratings to 0-4 for BERT
if train['rating'].max() == 5:
    train['rating'] = train['rating'] - 1

# Calculate balanced weights
weights = compute_class_weight(
    class_weight='balanced',
    classes=np.unique(train['rating']),
    y=train['rating']
)
class_weights = torch.tensor(weights, dtype=torch.float).to(device)

# Convert to Hugging Face Dataset
hf_dataset = Dataset.from_pandas(train[['text', 'rating']].rename(columns={'rating': 'labels'}))
dataset = hf_dataset.train_test_split(test_size=0.1)

# Tokenization
tokenizer = DistilBertTokenizerFast.from_pretrained("distilbert-base-uncased")

def tokenize(batch):
    return tokenizer(batch["text"], padding="max_length", truncation=True, max_length=128)

tokenized_dataset = dataset.map(tokenize, batched=True)

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

Map:   0%|          | 0/259200 [00:00<?, ? examples/s]

Map:   0%|          | 0/28800 [00:00<?, ? examples/s]

In [33]:
class WeightedTrainer(Trainer):
    # We add 'num_items_in_batch=None' and '**kwargs' to match the new library requirements
    def compute_loss(self, model, inputs, return_outputs=False, num_items_in_batch=None, **kwargs):
        labels = inputs.get("labels")
        
        # Standard Forward pass
        outputs = model(**inputs)
        logits = outputs.get("logits")
        
        # Our custom Weighted Loss logic (stays the same)
        loss_fct = nn.CrossEntropyLoss(weight=class_weights)
        loss = loss_fct(logits.view(-1, self.model.config.num_labels), labels.view(-1))
        
        return (loss, outputs) if return_outputs else loss

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    predictions = np.argmax(logits, axis=-1)
    return {
        "accuracy": accuracy_score(labels, predictions),
        "f1": f1_score(labels, predictions, average="macro")
    }

In [34]:
model = DistilBertForSequenceClassification.from_pretrained(
    "distilbert-base-uncased", 
    num_labels=5
).to(device)

training_args = TrainingArguments(
    output_dir="./distilbert_final",
    num_train_epochs=2,              # 2 epochs is the sweet spot for 288k rows
    per_device_train_batch_size=32,  # Optimized for 8GB+ VRAM GPUs
    eval_strategy="epoch",           # Evaluate once per hour to save time
    save_strategy="epoch",
    learning_rate=2e-5,
    weight_decay=0.01,
    fp16=True,                       # Enables Mixed Precision (Speed Boost)
    load_best_model_at_end=True,
    report_to="none"
)

trainer = WeightedTrainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_dataset["train"],
    eval_dataset=tokenized_dataset["test"],
    compute_metrics=compute_metrics
)

# This will likely take 1.5 to 2.5 hours total
trainer.train()

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_transform.bias    | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
vocab_layer_norm.weight | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
classifier.weight       | MISSING    |
classifier.bias         | MISSING    |
pre_classifier.weight   | MISSING    |
pre_classifier.bias     | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
C:\Users\hafee\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\torch\utils\data\dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

KeyboardInterrupt:

In [35]:
import torch
print(f"PyTorch version: {torch.__version__}")
print(f"Is CUDA available? {torch.cuda.is_available()}")
if torch.cuda.is_available():
    print(f"GPU Name: {torch.cuda.get_device_name(0)}")
else:
    print("WARNING: CUDA is NOT detected. The code is using the slow CPU.")

PyTorch version: 2.11.0+cpu
Is CUDA available? False
WARNING: CUDA is NOT detected. The code is using the slow CPU.

In [ ]:
pip uninstall torch torchvision torchaudio -y
pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121