<a href="https://colab.research.google.com/github/mf2056/F20AA_CW2/blob/main/Step4%265.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [55]:
import pandas as pd

In [31]:
train = pd.read_csv("/content/drive/MyDrive/train_processed.csv")

train.head()

,text,rating,tokens,stemmed,lemmatized,text_stem,text_lemma,review_length
0,this place is terrible the people in charge ar...,2,"['place', 'terrible', 'people', 'charge', 'wor...","['place', 'terribl', 'peopl', 'charg', 'worst'...","['place', 'terrible', 'people', 'charge', 'wor...",place terribl peopl charg worst part far yeah ...,place terrible people charge worst part far ye...,97
1,terrible service and they are saying that i ne...,1,"['terrible', 'service', 'saying', 'never', 'us...","['terribl', 'servic', 'say', 'never', 'use', '...","['terrible', 'service', 'saying', 'never', 'us...",terribl servic say never use servic lie call n...,terrible service saying never used service lie...,48
2,absolutely terrible company they sent me to co...,1,"['absolutely', 'terrible', 'company', 'sent', ...","['absolut', 'terribl', 'compani', 'sent', 'col...","['absolutely', 'terrible', 'company', 'sent', ...",absolut terribl compani sent collect without a...,absolutely terrible company sent collection wi...,211
3,to find it either park in front of the tuesday...,4,"['find', 'either', 'park', 'front', 'tuesday',...","['find', 'either', 'park', 'front', 'tuesday',...","['find', 'either', 'park', 'front', 'tuesday',...",find either park front tuesday morn mall entra...,find either park front tuesday morning mall en...,66
4,mall location used their services for sedan ni...,4,"['mall', 'location', 'used', 'services', 'seda...","['mall', 'locat', 'use', 'servic', 'sedan', 'n...","['mall', 'location', 'used', 'service', 'sedan...",mall locat use servic sedan nice perhap inform...,mall location used service sedan nice perhaps ...,28

In [41]:
import pandas as pd
import numpy as np

from sklearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV

from sklearn.feature_extraction.text import TfidfVectorizer

from sklearn.metrics import classification_report

In [42]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC
from sklearn.ensemble import RandomForestClassifier

from xgboost import XGBClassifier

In [43]:
train.isnull().sum()

text             43
rating            0
tokens            0
stemmed           0
lemmatized        0
text_stem         0
text_lemma        0
review_length     0
dtype: int64

In [44]:
train["text_lemma"] = train["text_lemma"].fillna("")
train["text_lemma"] = train["text_lemma"].astype(str)

train["text_stem"] = train["text_stem"].fillna("")
train["text_stem"] = train["text_stem"].astype(str)

X = train["text_lemma"]
Y = train["rating"]

In [45]:
train.shape

(288000, 8)

In [47]:
train.isnull().sum()

text             43
rating            0
tokens            0
stemmed           0
lemmatized        0
text_stem         0
text_lemma        0
review_length     0
dtype: int64

In [48]:
import pandas as pd
from sklearn.model_selection import GridSearchCV

def run_gridsearch(name, pipeline, params):
    # 1. Define multiple metrics
    scoring = {
        'Accuracy': 'accuracy',
        'MacroF1': 'f1_macro'
    }

    grid = GridSearchCV(
        pipeline,
        params,
        cv=3,
        n_jobs=-1,
        verbose=1,
        scoring=scoring,
        refit='MacroF1',
        return_train_score=False
    )

    grid.fit(X, Y)

    # 2. Extract detailed results into a table
    results_df = pd.DataFrame(grid.cv_results_)

    # Select columns for the 3 folds and the means
    columns_to_show = ['params']
    # Add Accuracy columns
    columns_to_show += ['split0_test_Accuracy', 'split1_test_Accuracy', 'split2_test_Accuracy', 'mean_test_Accuracy']
    # Add F1 columns
    columns_to_show += ['split0_test_MacroF1', 'split1_test_MacroF1', 'split2_test_MacroF1', 'mean_test_MacroF1']

    report_table = results_df[columns_to_show].sort_values('mean_test_MacroF1', ascending=False)

    print(f"\n==== {name} DETAILED FOLD RESULTS ====")
    print(report_table.to_string(index=False))

    # 3. Print the absolute bests
    best_f1_idx = results_df['mean_test_MacroF1'].idxmax()
    best_acc_idx = results_df['mean_test_Accuracy'].idxmax()

    print(f"\n--- {name} Summary ---")
    print(f"Best Params (for F1): {grid.best_params_}")
    print(f"Best Mean Macro-F1: {results_df.loc[best_f1_idx, 'mean_test_MacroF1']:.4f}")
    print(f"Best Mean Accuracy: {results_df.loc[best_acc_idx, 'mean_test_Accuracy']:.4f}")

    return grid

In [49]:
nb_pipeline = Pipeline([
    ("tfidf", TfidfVectorizer()),
    ("clf", MultinomialNB())
])

nb_params = {
    "clf__alpha": [0.1, 0.5, 1.0],
    "tfidf__ngram_range": [(1, 1), (1, 2)],
    "tfidf__max_features": [10000, 20000, 50000]
}

nb_grid = run_gridsearch(
    "Naive Bayes",
    nb_pipeline,
    nb_params
)

Fitting 3 folds for each of 18 candidates, totalling 54 fits

==== Naive Bayes DETAILED FOLD RESULTS ====
                                                                         params  split0_test_Accuracy  split1_test_Accuracy  split2_test_Accuracy  mean_test_Accuracy  split0_test_MacroF1  split1_test_MacroF1  split2_test_MacroF1  mean_test_MacroF1
{'clf__alpha': 0.1, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 2)}              0.637219              0.636490              0.635531            0.636413             0.465647             0.465948             0.465692           0.465763
{'clf__alpha': 0.1, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 2)}              0.635490              0.634865              0.634031            0.634795             0.455449             0.456240             0.457453           0.456381
{'clf__alpha': 0.5, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 2)}              0.635573              0.634500              0.634583            0.634885             0.445423             0.445651             0.448154           0.446409
{'clf__alpha': 0.1, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 2)}              0.632854              0.632146              0.631437            0.632146             0.445820             0.444637             0.446276           0.445577
{'clf__alpha': 0.5, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 2)}              0.636573              0.636625              0.635854            0.636351             0.439673             0.441473             0.441371           0.440839
{'clf__alpha': 0.5, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 2)}              0.632927              0.632094              0.631031            0.632017             0.440881             0.439504             0.440533           0.440306
{'clf__alpha': 1.0, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 2)}              0.631896              0.631344              0.630406            0.631215             0.432682             0.432268             0.433018           0.432656
{'clf__alpha': 1.0, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 2)}              0.634240              0.632927              0.633563            0.633576             0.430371             0.430254             0.432765           0.431130
{'clf__alpha': 0.1, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 1)}              0.619062              0.616781              0.616500            0.617448             0.416855             0.415051             0.415831           0.415913
{'clf__alpha': 0.1, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 1)}              0.620729              0.618469              0.618281            0.619160             0.414511             0.413304             0.413827           0.413881
{'clf__alpha': 0.1, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 1)}              0.615271              0.614135              0.612521            0.613976             0.411389             0.410384             0.409313           0.410362
{'clf__alpha': 0.5, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 1)}              0.620448              0.618500              0.618010            0.618986             0.408476             0.407876             0.408146           0.408166
{'clf__alpha': 1.0, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 2)}              0.632010              0.629823              0.629906            0.630580             0.405300             0.404131             0.404143           0.404525
{'clf__alpha': 0.5, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 1)}              0.617854              0.616833              0.615917            0.616868             0.400975             0.400758             0.401206           0.400980
{'clf__alpha': 1.0, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 1)}              0.618938              0.617302              0.617260            0.617833             0.399454             0.398902             0.400169           0.399509
{'clf__alpha': 1.0, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 1)}              0.612792              0.612625              0.611698            0.612372             0.378080             0.379572             0.379128           0.378927
{'clf__alpha': 0.5, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 1)}              0.609052              0.608615              0.606156            0.607941             0.365782             0.366203             0.363655           0.365214
{'clf__alpha': 1.0, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 1)}              0.598656              0.597427              0.596281            0.597455             0.325537             0.325276             0.323934           0.324916

--- Naive Bayes Summary ---
Best Params (for F1): {'clf__alpha': 0.1, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 2)}
Best Mean Macro-F1: 0.4658
Best Mean Accuracy: 0.6364

In [51]:
lr_pipeline = Pipeline([
    ("tfidf", TfidfVectorizer()),
    ("clf", LogisticRegression(max_iter=1000))
])

lr_params = {
    "clf__C": [0.5, 1, 3],
    "tfidf__ngram_range": [(1, 1), (1, 2)],
    "tfidf__max_features": [10000, 20000, 50000]
}

lr_grid = run_gridsearch(
    "Logistic Regression",
    lr_pipeline,
    lr_params
)

Fitting 3 folds for each of 18 candidates, totalling 54 fits

==== Logistic Regression DETAILED FOLD RESULTS ====
                                                                     params  split0_test_Accuracy  split1_test_Accuracy  split2_test_Accuracy  mean_test_Accuracy  split0_test_MacroF1  split1_test_MacroF1  split2_test_MacroF1  mean_test_MacroF1
  {'clf__C': 3, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 2)}              0.647729              0.647885              0.648146            0.647920             0.510176             0.509683             0.511105           0.510321
  {'clf__C': 3, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 2)}              0.651542              0.649958              0.650062            0.650521             0.510756             0.508212             0.511439           0.510136
  {'clf__C': 3, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 2)}              0.646333              0.646010              0.646323            0.646222             0.508253             0.508825             0.512554           0.509877
  {'clf__C': 1, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 2)}              0.657448              0.655427              0.654552            0.655809             0.505192             0.501824             0.504632           0.503882
  {'clf__C': 1, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 2)}              0.656573              0.654563              0.654302            0.655146             0.503656             0.500752             0.505162           0.503190
  {'clf__C': 1, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 2)}              0.657469              0.655490              0.654615            0.655858             0.503323             0.501926             0.502848           0.502699
  {'clf__C': 3, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 1)}              0.644823              0.643792              0.644146            0.644253             0.498342             0.496925             0.499301           0.498189
  {'clf__C': 3, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 1)}              0.644115              0.643531              0.643615            0.643753             0.496936             0.497387             0.499670           0.497998
  {'clf__C': 3, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 1)}              0.646094              0.645583              0.644802            0.645493             0.498551             0.496668             0.498754           0.497991
{'clf__C': 0.5, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 2)}              0.657469              0.655563              0.654813            0.655948             0.493790             0.491592             0.494944           0.493442
{'clf__C': 0.5, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 2)}              0.658583              0.656563              0.655865            0.657003             0.494891             0.491136             0.494138           0.493388
  {'clf__C': 1, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 1)}              0.650177              0.649583              0.649604            0.649788             0.491135             0.490732             0.493256           0.491708
  {'clf__C': 1, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 1)}              0.650500              0.649188              0.648615            0.649434             0.491710             0.490552             0.491780           0.491348
  {'clf__C': 1, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 1)}              0.650698              0.649500              0.649135            0.649778             0.490955             0.489986             0.492798           0.491246
{'clf__C': 0.5, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 2)}              0.658260              0.655458              0.655844            0.656521             0.489980             0.486335             0.491203           0.489173
{'clf__C': 0.5, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 1)}              0.651698              0.650250              0.649448            0.650465             0.482420             0.480971             0.483125           0.482172
{'clf__C': 0.5, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 1)}              0.651521              0.650010              0.649115            0.650215             0.482588             0.480785             0.483101           0.482158
{'clf__C': 0.5, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 1)}              0.651052              0.650198              0.649635            0.650295             0.480759             0.480178             0.482465           0.481134

--- Logistic Regression Summary ---
Best Params (for F1): {'clf__C': 3, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 2)}
Best Mean Macro-F1: 0.5103
Best Mean Accuracy: 0.6570

In [56]:
svm_pipeline = Pipeline([
    ("tfidf", TfidfVectorizer(
    )),
    ("clf", LinearSVC())
])

svm_params = {
    "clf__C": [0.5, 1, 2],
    "tfidf__ngram_range": [(1, 1), (1, 2)],
    "tfidf__max_features": [10000, 20000, 50000]
}

svm_grid = run_gridsearch(
    "SVM",
    svm_pipeline,
    svm_params
)

Fitting 3 folds for each of 18 candidates, totalling 54 fits

==== SVM DETAILED FOLD RESULTS ====
                                                                     params  split0_test_Accuracy  split1_test_Accuracy  split2_test_Accuracy  mean_test_Accuracy  split0_test_MacroF1  split1_test_MacroF1  split2_test_MacroF1  mean_test_MacroF1
  {'clf__C': 2, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 2)}              0.636646              0.635865              0.636083            0.636198             0.489704             0.489794             0.493818           0.491105
{'clf__C': 0.5, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 2)}              0.644823              0.643312              0.643302            0.643813             0.489808             0.489903             0.493333           0.491014
  {'clf__C': 1, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 2)}              0.632250              0.631396              0.631490            0.631712             0.489493             0.490090             0.492892           0.490825
  {'clf__C': 1, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 2)}              0.642365              0.641927              0.641687            0.641993             0.488896             0.489396             0.493458           0.490583
{'clf__C': 0.5, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 2)}              0.648687              0.646969              0.647375            0.647677             0.486875             0.487073             0.490811           0.488253
  {'clf__C': 2, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 2)}              0.616948              0.615635              0.617083            0.616556             0.485217             0.485928             0.488676           0.486607
  {'clf__C': 2, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 2)}              0.647667              0.645906              0.645969            0.646514             0.486029             0.483722             0.487669           0.485807
  {'clf__C': 1, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 2)}              0.649323              0.647594              0.647479            0.648132             0.484924             0.482709             0.486402           0.484678
{'clf__C': 0.5, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 2)}              0.651396              0.649698              0.649813            0.650302             0.482122             0.480545             0.484496           0.482388
  {'clf__C': 1, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 1)}              0.637156              0.633938              0.635448            0.635514             0.470233             0.467456             0.471438           0.469709
  {'clf__C': 2, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 1)}              0.633677              0.630229              0.631552            0.631819             0.470131             0.466606             0.471551           0.469429
  {'clf__C': 1, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 1)}              0.639573              0.635750              0.636802            0.637375             0.470268             0.466934             0.470884           0.469362
  {'clf__C': 2, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 1)}              0.629271              0.626625              0.627583            0.627826             0.469458             0.466793             0.470447           0.468899
{'clf__C': 0.5, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 1)}              0.643781              0.639719              0.641229            0.641576             0.468633             0.464722             0.469156           0.467504
{'clf__C': 0.5, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 1)}              0.644573              0.640771              0.641906            0.642417             0.468632             0.464587             0.469114           0.467444
  {'clf__C': 2, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 1)}              0.640385              0.636719              0.638219            0.638441             0.467668             0.465065             0.469217           0.467317
  {'clf__C': 1, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 1)}              0.643042              0.639323              0.640677            0.641014             0.467284             0.464643             0.469048           0.466992
{'clf__C': 0.5, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 1)}              0.645906              0.641469              0.642813            0.643396             0.466162             0.461992             0.467239           0.465131

--- SVM Summary ---
Best Params (for F1): {'clf__C': 2, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 2)}
Best Mean Macro-F1: 0.4911
Best Mean Accuracy: 0.6503

In [57]:
from sklearn.linear_model import SGDClassifier

sgd_pipeline = Pipeline([
    ("tfidf", TfidfVectorizer()), # Parameters handled by grid
    ("clf", SGDClassifier(max_iter=1000, tol=1e-3, random_state=25))
])

sgd_params = {
    "clf__alpha": [0.0001, 0.001, 0.01],
    "tfidf__ngram_range": [(1, 1), (1, 2)],
    "tfidf__max_features": [10000, 50000]
}

sgd_grid = run_gridsearch("SGD Classifier", sgd_pipeline, sgd_params)

Fitting 3 folds for each of 12 candidates, totalling 36 fits

==== SGD Classifier DETAILED FOLD RESULTS ====
                                                                            params  split0_test_Accuracy  split1_test_Accuracy  split2_test_Accuracy  mean_test_Accuracy  split0_test_MacroF1  split1_test_MacroF1  split2_test_MacroF1  mean_test_MacroF1
{'clf__alpha': 0.0001, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 2)}              0.635687              0.633729              0.633042            0.634153             0.403259             0.402127             0.403054           0.402813
{'clf__alpha': 0.0001, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 1)}              0.633646              0.630354              0.630990            0.631663             0.399573             0.397721             0.399907           0.399067
{'clf__alpha': 0.0001, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 1)}              0.632479              0.629667              0.629719            0.630622             0.396445             0.395405             0.396860           0.396237
{'clf__alpha': 0.0001, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 2)}              0.633292              0.631292              0.630865            0.631816             0.396397             0.395277             0.396479           0.396051
 {'clf__alpha': 0.001, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 2)}              0.594510              0.591865              0.592917            0.593097             0.333135             0.330743             0.331570           0.331816
 {'clf__alpha': 0.001, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 1)}              0.595417              0.592531              0.593021            0.593656             0.329854             0.328127             0.328653           0.328878
 {'clf__alpha': 0.001, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 1)}              0.593458              0.590500              0.591219            0.591726             0.325984             0.323622             0.324759           0.324788
 {'clf__alpha': 0.001, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 2)}              0.584979              0.583073              0.584052            0.584035             0.322538             0.321204             0.322364           0.322035
  {'clf__alpha': 0.01, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 2)}              0.571729              0.569104              0.569469            0.570101             0.308391             0.307156             0.307421           0.307656
  {'clf__alpha': 0.01, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 2)}              0.569958              0.566583              0.568000            0.568181             0.306720             0.304309             0.305503           0.305511
  {'clf__alpha': 0.01, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 1)}              0.566500              0.562656              0.564219            0.564458             0.295936             0.292747             0.293887           0.294190
  {'clf__alpha': 0.01, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 1)}              0.567187              0.563760              0.564740            0.565229             0.295363             0.292582             0.293508           0.293818

--- SGD Classifier Summary ---
Best Params (for F1): {'clf__alpha': 0.0001, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 2)}
Best Mean Macro-F1: 0.4028
Best Mean Accuracy: 0.6342

In [58]:
from sklearn.linear_model import RidgeClassifier

ridge_pipeline = Pipeline([
    ("tfidf", TfidfVectorizer()),
    ("clf", RidgeClassifier(random_state=28))
])

ridge_params = {
    "tfidf__ngram_range": [(1, 1), (1, 2)],  # Comparison requirement [cite: 39]
    "tfidf__max_features": [10000, 50000],   # Representation requirement [cite: 38]
    "clf__alpha": [0.1, 1.0, 10.0]           # The "knob" for regularization
}

ridge_grid = run_gridsearch("Ridge Classifier", ridge_pipeline, ridge_params)

Fitting 3 folds for each of 12 candidates, totalling 36 fits

==== Ridge Classifier DETAILED FOLD RESULTS ====
                                                                          params  split0_test_Accuracy  split1_test_Accuracy  split2_test_Accuracy  mean_test_Accuracy  split0_test_MacroF1  split1_test_MacroF1  split2_test_MacroF1  mean_test_MacroF1
 {'clf__alpha': 1.0, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 2)}              0.642354              0.640563              0.640708            0.641208             0.476540             0.475902             0.479258           0.477233
 {'clf__alpha': 0.1, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 2)}              0.609510              0.607906              0.608927            0.608781             0.469053             0.468478             0.473190           0.470240
 {'clf__alpha': 0.1, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 2)}              0.645167              0.643719              0.643240            0.644042             0.467612             0.465768             0.469419           0.467600
 {'clf__alpha': 1.0, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 2)}              0.647740              0.645760              0.645344            0.646281             0.465441             0.463398             0.467073           0.465304
 {'clf__alpha': 1.0, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 1)}              0.638365              0.635229              0.635333            0.636309             0.451298             0.448372             0.451321           0.450330
 {'clf__alpha': 0.1, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 1)}              0.636427              0.633938              0.634000            0.634788             0.449452             0.447689             0.450267           0.449136
{'clf__alpha': 10.0, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 2)}              0.651583              0.649500              0.649104            0.650062             0.448938             0.445682             0.449507           0.448042
 {'clf__alpha': 1.0, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 1)}              0.640781              0.637687              0.637948            0.638806             0.448464             0.445549             0.449217           0.447743
{'clf__alpha': 10.0, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 2)}              0.649177              0.647031              0.647094            0.647767             0.447482             0.445331             0.449296           0.447370
 {'clf__alpha': 0.1, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 1)}              0.614625              0.613260              0.613104            0.613663             0.446330             0.445159             0.446552           0.446014
{'clf__alpha': 10.0, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 1)}              0.644229              0.641083              0.641437            0.642250             0.434886             0.432024             0.435084           0.433998
{'clf__alpha': 10.0, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 1)}              0.644292              0.641708              0.641990            0.642663             0.433480             0.431675             0.434647           0.433267

--- Ridge Classifier Summary ---
Best Params (for F1): {'clf__alpha': 1.0, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 2)}
Best Mean Macro-F1: 0.4772
Best Mean Accuracy: 0.6501

In [ ]:
x = train["text_stem"]
y = train["rating"]

In [ ]:
import pandas as pd
from sklearn.model_selection import GridSearchCV

def run_gridsearch(name, pipeline, params):
    # 1. Define multiple metrics
    scoring = {
        'Accuracy': 'accuracy',
        'MacroF1': 'f1_macro'
    }

    grid_st = GridSearchCV(
        pipeline,
        params,
        cv=3,
        n_jobs=-1,
        verbose=1,
        scoring=scoring,
        refit='MacroF1',
        return_train_score=False
    )

    grid_st.fit(x, y)

    # 2. Extract detailed results into a table
    results_df = pd.DataFrame(grid_st.cv_results_)

    # Select columns for the 3 folds and the means
    columns_to_show = ['params']
    # Add Accuracy columns
    columns_to_show += ['split0_test_Accuracy', 'split1_test_Accuracy', 'split2_test_Accuracy', 'mean_test_Accuracy']
    # Add F1 columns
    columns_to_show += ['split0_test_MacroF1', 'split1_test_MacroF1', 'split2_test_MacroF1', 'mean_test_MacroF1']

    report_table = results_df[columns_to_show].sort_values('mean_test_MacroF1', ascending=False)

    print(f"\n==== {name} DETAILED FOLD RESULTS ====")
    print(report_table.to_string(index=False))

    # 3. Print the absolute bests
    best_f1_idx = results_df['mean_test_MacroF1'].idxmax()
    best_acc_idx = results_df['mean_test_Accuracy'].idxmax()

    print(f"\n--- {name} Summary ---")
    print(f"Best Params (for F1): {grid_st.best_params_}")
    print(f"Best Mean Macro-F1: {results_df.loc[best_f1_idx, 'mean_test_MacroF1']:.4f}")
    print(f"Best Mean Accuracy: {results_df.loc[best_acc_idx, 'mean_test_Accuracy']:.4f}")

    return grid_st

In [ ]:
nb_pipeline = Pipeline([
    ("tfidf", TfidfVectorizer()),
    ("clf", MultinomialNB())
])

nb_params = {
    "clf__alpha": [0.1, 0.5, 1.0],
    "tfidf__ngram_range": [(1, 1), (1, 2)],
    "tfidf__max_features": [10000, 20000, 50000]
}

nb_grid = run_gridsearch(
    "Naive Bayes",
    nb_pipeline,
    nb_params
)

Fitting 3 folds for each of 18 candidates, totalling 54 fits

In [ ]:
lr_pipeline = Pipeline([
    ("tfidf", TfidfVectorizer()),
    ("clf", LogisticRegression(max_iter=1000))
])

lr_params = {
    "clf__C": [0.5, 1, 3],
    "tfidf__ngram_range": [(1, 1), (1, 2)],
    "tfidf__max_features": [10000, 20000, 50000]
}

lr_grid = run_gridsearch(
    "Logistic Regression",
    lr_pipeline,
    lr_params
)

In [ ]:
svm_pipeline = Pipeline([
    ("tfidf", TfidfVectorizer(
        ngram_range=(1,2),
        max_features=50000
    )),
    ("clf", LinearSVC())
])

svm_params = {
    "clf__C": [0.5, 1, 2],
    "tfidf__ngram_range": [(1, 1), (1, 2)],
    "tfidf__max_features": [10000, 20000, 50000]
}

svm_grid = run_gridsearch(
    "SVM",
    svm_pipeline,
    svm_params
)

In [ ]:
from sklearn.linear_model import SGDClassifier

sgd_pipeline = Pipeline([
    ("tfidf", TfidfVectorizer()), # Parameters handled by grid
    ("clf", SGDClassifier(max_iter=1000, tol=1e-3, random_state=25))
])

sgd_params = {
    "clf__alpha": [0.0001, 0.001, 0.01],
    "tfidf__ngram_range": [(1, 1), (1, 2)],
    "tfidf__max_features": [10000, 50000]
}

sgd_grid = run_gridsearch("SGD Classifier", sgd_pipeline, sgd_params)

In [ ]:
from sklearn.linear_model import RidgeClassifier

ridge_pipeline = Pipeline([
    ("tfidf", TfidfVectorizer()),
    ("clf", RidgeClassifier(random_state=28))
])

ridge_params = {
    "tfidf__ngram_range": [(1, 1), (1, 2)],  # Comparison requirement [cite: 39]
    "tfidf__max_features": [10000, 50000],   # Representation requirement [cite: 38]
    "clf__alpha": [0.1, 1.0, 10.0]           # The "knob" for regularization
}

ridge_grid = run_gridsearch("Ridge Classifier", ridge_pipeline, ridge_params)